spring.application.name=UserAuthentication
spring.datasource.url=jdbc:mysql://localhost:3307/userAuth
spring.datasource.username=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymleaf.cache=false


#logging
logging.level.root=INFO

spring.security.user.name= user
spring.security.user.password=user

logging.level.org.springframework.security=trace

jwt.secret=this-is-my-jwt-authorization-tokenization-secure-secure
jwt.expiration-ms=3600000

spring.security.oauth2.client.registration.github.client-id=Iv23limdgEcEEcyV3f8d
spring.security.oauth2.client.registration.github.client-secret=2c76f0e846f8a7f284f07107d11ef35e8799f57d

